name: Run Gosec

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run Gosec security scanner
      uses: securego/gosec@master
      with:
        args: ./...